version: '3.8'
services:
  db:
    container_name: postgresql
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - netflix_network

  backend:
    container_name: netflix_backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - netflix_network

  frontend:
    container_name: netflix_frontend
    build:
      context: ./frontend/vite-project
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - netflix_network

networks:
  netflix_network:
    driver: bridge

volumes:
  db-data:
